### ISSUE TITLE
CavTools 2.1

### ISSUE THREAD

**Issue by MattTreck** [Jarvvski/CavTools#153]
<h2>problem</h2>

treck wants stuff

<hr>

<h2>solution</h2>

do what treck wants

<hr>

<h2>CavTools 2.1</h2>

To be done immediately after the meeting tracker is released. (We'll keep that as 2.0.95)
- Consolidate the option menus into their own ACP tab in the control panel.
- Restructure certain option fields that can be re-used (the ADR and the AWOL Tracker both have positions listed when we could just have them in one place). These types of options that apply to more than one part of CavTools can be in their own "global options" page.
- If the code base needs to be restructured now that we're getting bigger, this would be the time to do it. This update is going to be focussed on the back-end.

**Comment by Jarvvski** [comment]
Switched to 2.2 so that I can focus on finishing off the outlying tools needed for 2.1
