### ISSUE TITLE
Enlistment Tracker Default Graph

### ISSUE THREAD

**Issue by MattTreck** [Jarvvski/CavTools#154]
<h2>problem</h2>
treck want stuff
<hr>
<h2>solution</h2>
do what treck wants

Set the default graph in the enlistment manager to the line graph, the yearly in-depth. As it provides more useful information for the present than the quarterly graph.

**Comment by Jarvvski** [comment]
0ee69edc78b1deda0d7428ab65c8ca258fcaf572
