### ISSUE TITLE
Automated Avatar System

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#160]
<h2>Problem</h2><br />After Promotions you may easily forget to update your Avatar manually.<br /><hr><h2>Reason</h2><br />If this System is bound to MILPACS it will get updated by S1 aswell, just like the TS3 Permissions.<br><br>-Staff Sergeant Sharkey.D

**Comment by CollinsG-7Cav** [comment]
Process flow unnecessary - marked with flow so not opened by me again
