### ISSUE TITLE
mentions of organizational units / positions

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#166]
<h2>Problem</h2><br />Idea: Introducing 'anonymous' accounts based on roles and positions which can be connected to multiple real users. E.g.: A posting containing @rrd produces an alert for the CO, XO and NCOIC of RRD, @tucomp for CO, XO and 1SG of TU @d17milpacs for the D/1-7 milpacs clerk(s), you get the idea.
While this supports the bad practice of 'solving' issues by just tagging people, it would at least reduce delays due to absence of the single one mentioned person and would have the same effect as writing a PM to the same personnel, without having to even know their names.<br /><hr><h2>Reason</h2><br />In the enlistment or personnel office areas of the forum, issues are often addressed towards individual members of certain departments (i.e. @sharkey for anything S1), instead of writing PMs to the respective personnel. If that one person is absent and/or not in fact responsible the resolution of the initial problem is delayed and more personnel than needed are bothered.<br><br>-Staff Sergeant Wiese.M

**Comment by Jarvvski** [comment]
Could use # tags instead. @ symbols are already uses within Xen for user mentions.

Would limit to only departments. Not sub units such as C/1-7 etc.
