### ISSUE TITLE
Change to the donation button

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#168]
<h2>Problem</h2><br />I would like to see if the functionality of the donation button can be changed to account for different types of donations.  I would like for there to be a check box for the type of donation such as  a "server fund" and "request for aide".  There should be a way for the donator to designate what their donation is for so to not effect the numbers in regards to how much we need for the server fund.<br /><hr><h2>Reason</h2><br />Currently anytime a donation is made via the donation button, the amount of the donation is added to the total of collected funds.  This number is skewed when there is a request for aide since we use the same button to collect those donations.  There should be a way to designate what the donation is for, and a way to change it on the backside should someone forget or fail to mark their donation correctly.<br><br>-General of the Army Chance.JT

**Comment by Jarvvski** [comment]
Will include in v2.2
