### ISSUE TITLE
Interest Finder

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#170]
<h2>Problem</h2><br /><br /><hr><h2>Reason</h2><br />So lets say we have the ability to add games, interests in our profile and after we did that we could then go to our profile and click on "Squad" and it would show all the members that have interest in Squad and so forth. This would make it easier for people to link up for games and other interests of that nature.<br><br>-Corporal Beckett.A

**Comment by Jarvvski** [comment]
Maybe one day. Not currently vital. Forums serve well for this.
