### ISSUE TITLE
S2 Quarterly Checks Automation

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#177]
<h2>Problem</h2><br />Investigators wasting time on GUID checks
Automate the system using code from RRD Enlistment tracker

Boom; 50 hours + annually saved<br /><hr><h2>Reason</h2><br />Automation

Duh<br><br>-Second Lieutenant Collins.G

**Comment by CollinsG-7Cav** [comment]
https://www.dropbox.com/s/hk5g46cksxjikh9/GITHUB5%20Process%20Flow%20-%20S2%20GUID%20Autochecker.pdf?dl=0
Process flow

**Comment by Jarvvski** [comment]
Done.
