### ISSUE TITLE
S2 Dashboard

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#178]
<h2>Problem</h2><br />1. Automatically assign random investigator to applicant folder
2. Track all open folders similar to RRD Tracker
3. Auto check VAC status (RRD tracker)
4. Auto check status (Private etc) 
5. Auto-archive when auto-deny?
6. Auto-format of past member notes/Discharge post?<br /><hr><h2>Reason</h2><br />Stuff<br><br>-Second Lieutenant Collins.G

**Comment by CollinsG-7Cav** [comment]
![image](https://cloud.githubusercontent.com/assets/21184525/21653805/d6ade9a4-d2aa-11e6-83ad-695ec16ec0f2.png)

**Comment by CollinsG-7Cav** [comment]
Process Flow

https://www.dropbox.com/s/61d2kls216w0kx1/GITHUB4%20Process%20Flow%20-%20S2%20Tracking.pdf?dl=0
