### ISSUE TITLE
WE NEED AN ABOUT US PAGE

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#179]
<h2>Problem</h2><br />We don't have one<br /><hr><h2>Reason</h2><br />We need one as currently public players can't see any broad information about the cav. Members who join the site for the first time can't find out any pertinent facts.

Needs to be modern, hipster, etc. Primarily for recruiting.<br><br>-First Lieutenant Richards.D

**Comment by MattTreck** [comment]
Assuming that the information is ready, let's try to hit this with 2.3

**Comment by CollinsG-7Cav** [comment]
No process flow necessary. 2.3 already assigned.
