### ISSUE TITLE
Enlistment MGMT tool.

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#180]
<h2>Problem</h2><br />The tool  doesn't seem show us the previous quarters stats for Insurgency, ACV or Squad.<br /><hr><h2>Reason</h2><br />Unknown.<br><br>-Sergeant First Class Ryan.B

**Comment by Jarvvski** [comment]
Fixed in 58091da83402bc8ad5f14e5dd96e2a65006cb7bc
