### ISSUE TITLE
Milpacs option in the profile dropbox

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#182]
<h2>Problem</h2><br />Theres no button to go straight to our own milpacs  when we hover our courser over our name in the uper right hand corner<br /><hr><h2>Reason</h2><br />Make it easier to get to our own milpacs, maybe in that empty spot above log out and to the right of the teamspeak option.<br><br>-Private First Class Greibrok.J

**Comment by CollinsG-7Cav** [comment]
Personally think this is unnecessary but, could be done?

Look at by Milestone 2.1
Do something by 2.3

**Comment by Jarvvski** [comment]
Close to being done. Just need finishing touches.

**Comment by Jarvvski** [comment]
Done.
