### ISSUE TITLE
Server cost break down for AOs

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#183]
<h2>Problem</h2><br />We used to be able to see how much each server costs via the donations page, this link has been removed (I am assuming because we changed hosts) and replacement has not been implemented.<br /><hr><h2>Reason</h2><br /><br><br>-Sergeant Rosfeld.M

**Comment by Jarvvski** [comment]
backside options, pie chart generator. Willdo in the future

**Comment by CollinsG-7Cav** [comment]
Milestone 2.3 

Based on data - just graph representing this data akin to regi-tracker.
Does not need process flow
