### ISSUE TITLE
BF1 Origins on Enlisment App

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#184]
<h2>Problem</h2><br />Could you please look into having a box to input applicant's Origins name on the enlistment form?<br /><hr><h2>Reason</h2><br />Makes it easier to track applicants<br><br>-Specialist Masse.P

**Comment by Jarvvski** [comment]
Will look into it

**Comment by CollinsG-7Cav** [comment]
Minor changes 2.1

**Comment by CollinsG-7Cav** [comment]
Does not need process flow

**Comment by Jarvvski** [comment]
Done
