### ISSUE TITLE
Enlistment Form Update

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#185]
<h2>Problem</h2><br />Please Add [PC] next to battlefield 1<br /><hr><h2>Reason</h2><br />We had a few recruits want to join who only play on PS4.<br><br>-First Lieutenant Lombardi.M

**Comment by Jarvvski** [comment]
Will look into it

**Comment by CollinsG-7Cav** [comment]
Added to 2.1 as minor change

**Comment by CollinsG-7Cav** [comment]
No process flow required.

**Comment by Jarvvski** [comment]
Fixed.
