### ISSUE TITLE
Recruit Tracker

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#186]
<h2>Problem</h2><br />Can not tell how many recruits a recruiter has gotten past the current month<br /><hr><h2>Reason</h2><br />Need to award medals for recruiting and also for retention purposes in the department.<br><br>-First Lieutenant Lombardi.M

**Comment by Jarvvski** [comment]
Will look into it

**Comment by CollinsG-7Cav** [comment]
Does not need process flow.
Data is captured in table somewhere for the month - it is simply a matter of adapting the enlistment manager graph for "Recruiter Monthly Tracker" to select the month and year from a dropdown?

2.2

**Comment by Jarvvski** [comment]
changing to 2.1

**Comment by Jarvvski** [comment]
Done
