### ISSUE TITLE
replace [class]-tag on classes with respective AO in cavtools

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#187]
<h2>Problem</h2><br />Right now all classes are posted in Class Announcements (https://7cav.us/forums/class-announcements.20/), yet still all get the prefix [class], which is redundant at that point.<br /><hr><h2>Reason</h2><br />Instead of using redundant information the AO or scope of that class could be used to make it easier to discern relevant classes
[ARMA], [SQUAD], as applicable [GENERAL] or [ANY] for things like NCOA<br><br>-Staff Sergeant Wiese.M

**Comment by Jarvvski** [comment]
Will look into it

**Comment by CollinsG-7Cav** [comment]
Minor change - can be done for 2.1? 

Process flow not necessary

Other changes to add to this;

In Event Form, add all AO titles and "ANY" option dropdown for all AOs and have this variable input to the string of the post topic name instead of [CLASS] Title.

**Comment by Jarvvski** [comment]
Done #200
