### ISSUE TITLE
New Status Recruitment TOol

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#189]
<h2>Problem</h2><br />WHen making an applicant change name the status stays open, requesting a new status that says "Pending Action" or equivalent<br /><hr><h2>Reason</h2><br />I can see a name as not being rude and think its good to go and notice the application is still in the open status and click approve only to learn one of the other recruiters do not like the name.<br><br>-First Lieutenant Lombardi.M

**Comment by CollinsG-7Cav** [comment]
Denied
OIC replaced, operator error, does not affect process at all.
