### ISSUE TITLE
School leads receive full access to the S3 Events tool

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#190]
<h2>Problem</h2><br />School Leads are unable to keep their own class posts up to date and have to go through S3 HQ which is unnecessary.<br /><hr><h2>Reason</h2><br />Below are the names who need access:

S3 - 1BN SOI Lead : Staff Sergeant Argus.J
S3 - 1BN SOA Lead : Lieutenant Colonel Baeder.S
S3 - 1BN CSS Lead : Sergeant First Class Draco.R
S3 - 1BN ACE Instructors : Major Abbassi.G
S3 - 1BN ATC Lead : Warrant Officer 1 Tidrow.D
S3 - 2BN SOI Lead : First Lieutenant Kibs.M
S3 - 2BN SOI Lead : First Lieutenant Rogers.S<br><br>-Sergeant Major Tully.B

**Comment by Jarvvski** [comment]
@mattTreck I don't have perm access

**Comment by CollinsG-7Cav** [comment]
Transferred to helpdesk as Perm issue.
