### ISSUE TITLE
S1 - Transfers/Appointments  Step 1-3 - Ball.C

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#191]
<h2>Problem</h2><br />Step 1 - Standard position announcement templates
Step 2 - Form using the above standard templates for non-S1 users to post announcements
Step 3 - Form automatically changes MILPACS but must be "approved / denied" by S1 Milpacs team<br /><hr><h2>Reason</h2><br />Automation / Standardisation

Leads on from former submission by Collins.G

Talk to Collins bout dis wan<br><br>-First Lieutenant Collins.G

**Comment by CollinsG-7Cav** [comment]
Full extent of process 
Process Failure Mode Effects Analysis: Not yet complete due to demand for Process Flows. TBD.

Process Flow (Code; GITHUB3) -
https://www.dropbox.com/s/rmyry9tgqkby9zx/GITHUB3%20Process%20Flow%20-%20S1%20Templates.pdf?dl=0
