### ISSUE TITLE
S3 Events

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#193]
<h2>Problem</h2><br />School leads need to be able to add and edit classes.  Also, please add the 2359Z time to the times.  We use it often and never use 0000.<br /><hr><h2>Reason</h2><br />Thank you<br><br>-Staff Sergeant Argus.J

**Comment by Jarvvski** [comment]
Ticket for school leads, send pm on TS.

Time will be in 2.1

**Comment by Jarvvski** [comment]
18f1d64b4b8784c07c4d3f1bb65112825b41251f

2359 time added
