### ISSUE TITLE
R&U Button

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#194]
<h2>Problem</h2><br />Have a button at the bottom of the OP that allows troopers to R&U without having to make a reply post. Is a checkbox option when creating a new thread.<br /><hr><h2>Reason</h2><br />Allow troopers to R&U without filling up the thread useless R&U so that the OP can see more clearly legit posts that ask questions or need more attention to. Essentially cut down on clutter, but still allow commanders to know that their troopers have R&U'd the post.<br><br>-Sergeant Windeck.S

**Comment by CollinsG-7Cav** [comment]
Unnecessary. If this is such a big deal it could be a regimental policy that R&U posts be accompanied by Polls for R&U Tracking
