### ISSUE TITLE
Enlistment Application

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#195]
<h2>Problem</h2><br />Currently, there is much confusion on exactly what the Steam 64 bit ID is. I have had multiple people confused on what to put and when I mention it's just the numbers, it is extremely clear.<br /><hr><h2>Reason</h2><br />If we put a picture, or highlight, or both combined, of the exact thing we are looking for on the page (even maybe the enlistment application itself), I think it will clear up much of the confusion and smooth out the enlistment process. 

- Sergeant Carter.D<br><br>-Sergeant Carter.D

**Comment by Jarvvski** [comment]
no.

There is literally a link in the application to a guide on _exactly_ how to find it.
