### ISSUE TITLE
Formatting Error on Rank Page

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#206]
<h2>Problem</h2><br />On this page https://7cav.us/wiki/Wiki-Pages/Officers there is a section that is not formatted correctly. In the Captain minimum requirement field someone forgot to close the list tag out correctly.<br /><hr><h2>Reason</h2><br />Just trying to make the website look as pristine as possible.<br><br>-Private First Class Perrett.J

**Comment by Jarvvski** [comment]
Not CavTools related.
