### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#209]
<h2>Problem</h2><br />I self-Identify as a TriSexual F22 FighterJet, I was wondering if I could change my gender to that.<br /><hr><h2>Reason</h2><br />Toussaint.C: Can I change my Sex to TriSexual F22 FighterJet
Jun 13, 2016

Jarvis.A: put in a feature request.<br><br>-Corporal Toussaint.C

**Comment by Jarvvski** [comment]
no
