### ISSUE TITLE
Ability for S2 to send mass PMs

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#213]
<h2>Problem</h2><br />Could S2 have the ability to send PMs to recruits about Holds etc just like the AWOL PM system. Also, would it be possible to have the ability to send mass PMs to Cav members when they flag up on the Quarterly checks ie if they don't have a Steam ID linked in the Arma 3 GUID Part.<br /><hr><h2>Reason</h2><br />To aid in greater efficiency with the S2 Department<br><br>-Corporal Cass.A

**Comment by Jarvvski** [comment]
Might have the intern have a go at having the system auto create a PM when user steam != public

Rest would be in some sort of an S2 dash which is longer term after MEGA test case
