### ISSUE TITLE
Discharged user tags are backwards.

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#214]
<h2>Problem</h2><br />My OCD. 

Real talk, it's just swapped. http://imgur.com/a/p6qj1<br /><hr><h2>Reason</h2><br />Iunno CSS just messed for now.<br><br>-Corporal Ari.M

**Comment by Jarvvski** [comment]
Ha that's amazing.

@MattTreck ?

**Comment by Jarvvski** [comment]
Fixed
