### ISSUE TITLE
GUID Auto Refresh

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#216]
<h2>Problem</h2><br />Some members for the AutoCheck are flagged for No Steam ID. Could there be a way for that list to be refreshed once those members have added their ID?<br /><hr><h2>Reason</h2><br />Automation and to save time<br><br>-Corporal Cass.A

**Comment by Jarvvski** [comment]
Not planning on auto checking the auto check. Defeats the purpose of the auto check
