### ISSUE TITLE
Team Speak Game Badges

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#220]
<h2>Problem</h2><br /><br /><hr><h2>Reason</h2><br />We could have Games Badges on Team Speak. I'm an Insurgency player, but I also have Squad and would like to play squad with other Cav members. But being a new member I don't know who are the guys that play Squad. And sometimes, when they are doing somekind of practice or training, it's common for the people taking part in it not to be on that specific game channel.

So having badges beside our names would make it easier for us to identify who plays what. Also it would make it easier for newcomers (recruits or not) that use our TS to find Recruiters and/or people that are into the games they like.<br><br>-Private Jarouche.N

**Comment by Jarvvski** [comment]
@MattTreck what do you think

**Comment by omegaRush** [comment]
Badges seem excessive and would make the interface more cluttered than it is. Maybe set descriptions for primary AOs (Arma, Squad, etc) instead. Not sure how flexible TS is for automating something like that though.

.02
