### ISSUE TITLE
LOA / ELOA post titles

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#222]
<h2>Problem</h2><br />When creating an LOA / ELOA post for someone else, the title is generated using the name of the person who submitted the report, instead of the person entered in the "name" field of the LOA / ELOA form.<br /><hr><h2>Reason</h2><br />Often SLs / Platoon Staff submit an LOA / ELOA request for one of their troopers.  For tracking LOAs / ELOAs it makes much more sense to be able to simply look at the title to see who is going on LOA than have to open up each individual post.<br><br>-Sergeant Major Tully.B

**Comment by Jarvvski** [comment]
If we ever go to full PAF work in CT, then this could work.

Until then, this is not part of CT
