### ISSUE TITLE
Break Line in Conversations

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#223]
<h2>Problem</h2><br />Can we get a break line in our Conversations page that separates out stickied conversations from our non-stickied ones. Just like in forums.<br /><hr><h2>Reason</h2><br />Allows a clear visual separation, just like in forums.<br><br>-Second Lieutenant Parsons.B

**Comment by Jarvvski** [comment]
I'll look into it, but this probably involves template changes which are a bitch to implement so I'm not promising anything
