### ISSUE TITLE
Improvement to AWOL tool.

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#228]
<h2>Problem</h2><br />Not really a problem, but I notice people's CoC go in after the potential AWOLs get posted and put an "@" then their name so they get a notification. Is it possible to automate that from the post/tool?<br /><hr><h2>Reason</h2><br />Cut down on the workload for many.<br><br>-Command Sergeant Major Bango.C

**Comment by Jarvvski** [comment]
done fcab2df6fdd1e4ae33bc23fae961491d5e2014fe
