### ISSUE TITLE
TAC 1- New Changes have overpowered Enemy Air Support capabilities

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#234]
<h2>Problem</h2><br />Even with a radio tower destroyed, the enemy will spawn in more aircraft that can physically be defended against, essentially removing friendly air capability.  Game balance must be fixed. 

Cheers,

Campbell<br /><hr><h2>Reason</h2><br />Gameplay Balance<br><br>-Private Campbell.D

**Comment by Jarvvski** [comment]
This is not s6
