### ISSUE TITLE
Request of Mil Pack uniform change.

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#242]
<h2>Problem</h2><br />Noticed that all the Mil Pack are in the Male Gender Standards.<br /><hr><h2>Reason</h2><br />Me being a female in the 7th cav this uniform would be outside of Army Regulation 670-1:14-11 and DA Pam 670–1:14-11.  Here is a link that shows the differences http://imgur.com/a/s45Ko<br><br>-Recruit Vanbrocklin.S

**Comment by Jarvvski** [comment]
lol no
