### ISSUE TITLE
Enhanced Movement

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#244]
<h2>Problem</h2><br />keep getting stuck on fences and unable to move freely around compounds etc<br /><hr><h2>Reason</h2><br />I believe we need to add this mod for more freedom of movement

http://www.armaholic.com/page.php?id=27224 

it is available on Steam aswell<br><br>-Private First Class Holmes.G

**Comment by Jarvvski** [comment]
Not S6.
