### ISSUE TITLE
Service restart announcement

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#247]
<h2>Problem</h2><br />Problem 1: Restarting live services without prior warning is bad practice and means progress towards MCC was lost.
Problem 2: Server didn't need restarting second time, the same ticket was resolved twice.<br /><hr><h2>Reason</h2><br />Live services are always restarted without warning. Tac 2 was highly populated and the server was restarted to update just before the MCC started, meaning that the person running the mission had no opportunity to save the file. We got in to the next map and had finally got back into the action and the server was restarted again for the same reason, despite already being updated.

Prior warning would have meant that progress could have been saved in both instances, along with prevention of the second restart.

Updating a service that people are using without prior notification is bad practice and disrupts gameplay. We've been playing for an hour without getting into contact as a result.<br><br>-Corporal Jagger.D

**Comment by MattTreck** [comment]
Boo goo
