### ISSUE TITLE
Google Docs BBCode Documentation

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#250]
<h2>Problem</h2><br />Google Docs BB Code documentation contained within a forum post that can be easily lost over time (https://7cav.us/threads/testing-google-docs-bb-code.32935/)<br /><hr><h2>Reason</h2><br />Request Google Docs BB Code documentation be added to website BB Code page (https://7cav.us/help/bb-codes)<br><br>-Sergeant First Class Bell.K

**Comment by Jarvvski** [comment]
I think that page is generated on its own. If the google docs BB stuff is playing around, then I'm not sure.

The Docs BB code is a custom plugin. Nothing internally created.
