### ISSUE TITLE
Reporting System

### ISSUE THREAD

**Issue by Jarvvski** [Jarvvski/CavTools#77]
### Problem

Managing reporting from platoon, company and battalion is time consuming and requires external PDFs.

<hr>
### Reason

Automation, duh.

<hr>
### Solution

Create system in response to PM feedback. Probably replicated page for each stage in COC with the ability to view completed forms in each stage beneath them.

**Comment by CollinsG-7Cav** [comment]
Tully requests

Platoon report: "X/Y Signed Roll Call.   Z/A Attended Practice" - "Troopers B, C, D did not attend/sign"

**Comment by CollinsG-7Cav** [comment]
PSG: "Reviewed Notes" checkbox + "Attended SP" + Notes box for where, leave open not closed options
PL/1SG/XO/CO

**Comment by CollinsG-7Cav** [comment]
Squad Level: Who attended SP, who didnt, notes

**Comment by CollinsG-7Cav** [comment]
Company get all platoon notes, SL notes, who didn't attend plus options for attending SP + notes box

**Comment by CollinsG-7Cav** [comment]
Want to see all details previously submitted in "Spoiler" equivalent
